spring.application.name=web1cuc-coffee

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=web1cuc_coffee;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect